# Generated by Django 5.1.3 on 2025-04-18 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_playerstatus_last_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_type", models.CharField(max_length=50)),
                ("state", models.JSONField()),
                ("timestamp", models.DateTimeField(auto_now=True)),
                (
                    "game_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_states",
                        to="games.gameroom",
                    ),
                ),
            ],
            options={
                "unique_together": {("game_room", "game_type")},
            },
        ),
    ]
