# Generated by Django 5.1.3 on 2025-04-18 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_gamestate"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GameState",
        ),
    ]
