# Generated by Django 5.1.3 on 2025-04-19 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0005_delete_gamestate"),
    ]

    operations = [
        migrations.CreateModel(
            name="LudoPlayerStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("red", "Red"),
                            ("blue", "Blue"),
                            ("green", "Green"),
                            ("yellow", "Yellow"),
                        ],
                        max_length=10,
                    ),
                ),
                ("pieces", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "player_status",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ludo_status",
                        to="games.playerstatus",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ludo Player Status",
                "verbose_name_plural": "Ludo Player Statuses",
            },
        ),
    ]
